#!/usr/bin/env bash
# pi-fast.sh: bundle the npm-installed pi coding agent into a single file for fast startup.
#
# Usage: bash pi-fast.sh [--no-update] [--install-dir <dir>] [--shim-dir <dir>]
#
# Rollback: delete pi in the shim dir and the whole install dir.

set -euo pipefail

# ---------------------------------------------------------------- defaults
INSTALL_DIR=""
SHIM_DIR="$HOME/.local/bin"
NO_UPDATE=0

# ---------------------------------------------------------------- arg parsing
while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-update)    NO_UPDATE=1; shift ;;
        --install-dir)  INSTALL_DIR="$2"; shift 2 ;;
        --shim-dir)     SHIM_DIR="$2"; shift 2 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# Mirror the PowerShell default: prefer D:/pi-dist if it exists.
# INSTALL_DIR is kept as a Unix-style path internally; we use cygpath -m
# when passing it to node/esbuild (which is a Windows process and needs
# C:/ style paths, not /c/ MSYS paths).
if [[ -z "$INSTALL_DIR" ]]; then
    if [[ -d "/d/pi-dist" ]]; then
        INSTALL_DIR="/d/pi-dist"
    else
        INSTALL_DIR="$(cygpath -u "$LOCALAPPDATA")/pi-dist"
    fi
fi

# ---------------------------------------------------------------- 1. locate npm + pi
echo "=== locating npm + pi ==="

# tr -d '\r\n': strip both CR and LF that npm may emit on Windows
NPM_ROOT="$(npm root -g | tr -d '\r\n')"
if [[ -z "$NPM_ROOT" ]]; then
    echo "ERROR: npm not found on PATH. Install Node.js (LTS) first: https://nodejs.org" >&2
    exit 1
fi

PKG_DIR="$NPM_ROOT/@earendil-works/pi-coding-agent"
# cygpath -m gives C:/... style paths that Windows node.exe can require()
PKG_JSON_MIX="$(cygpath -m "$PKG_DIR/package.json")"

if [[ ! -f "$PKG_DIR/dist/cli.js" ]]; then
    echo "pi is not installed yet - installing latest..."
    npm install -g --ignore-scripts "@earendil-works/pi-coding-agent"
fi

# ---------------------------------------------------------------- 2. optional upgrade
INSTALLED="$(node -p "require('$PKG_JSON_MIX').version" | tr -d '\r')"
echo "Installed version: $INSTALLED"

if [[ "$NO_UPDATE" -eq 0 ]]; then
    LATEST="$(npm view "@earendil-works/pi-coding-agent" version 2>/dev/null | tr -d '\r' || true)"
    if [[ -n "$LATEST" && "$LATEST" != "$INSTALLED" ]]; then
        echo "New version on npm: $INSTALLED -> $LATEST  (upgrading...)"
        npm install -g --ignore-scripts "@earendil-works/pi-coding-agent@latest"
        INSTALLED="$(node -p "require('$PKG_JSON_MIX').version" | tr -d '\r')"
    elif [[ -n "$LATEST" ]]; then
        echo "pi $INSTALLED is already the latest on npm."
    else
        echo "(could not reach npm registry - skipping update check, rebuilding from $INSTALLED)"
    fi
fi

# ---------------------------------------------------------------- 3. bundle
echo "Bundling pi $INSTALLED -> $INSTALL_DIR/pi-single.mjs"
mkdir -p "$INSTALL_DIR"

# esbuild is a Windows binary here, so give it C:/ style paths
ENTRY_MIX="$(cygpath -m "$PKG_DIR/dist/cli.js")"
OUT_MIX="$(cygpath -m "$INSTALL_DIR")/pi-single.mjs"
BANNER="import { createRequire as __piCr } from 'module';var require = __piCr(import.meta.url);"

NODE_ARCH="$(node -p "process.arch" | tr -d '\r')"
if [[ "$NODE_ARCH" == "arm64" ]]; then
    CLIP="@mariozechner/clipboard-win32-arm64-msvc"
else
    CLIP="@mariozechner/clipboard-win32-x64-msvc"
fi

npx -y esbuild "$ENTRY_MIX" \
    --bundle \
    --platform=node \
    --format=esm \
    "--banner:js=$BANNER" \
    "--external:@earendil-works/pi-tui" \
    "--external:$CLIP" \
    "--outfile=$OUT_MIX" \
    --log-level=error

# ---------------------------------------------------------------- 4. copy runtime externals
echo "Copying runtime externals..."
NESTED="$PKG_DIR/node_modules"
TARGETS=(
    "@earendil-works/pi-tui"
    "@earendil-works/pi-agent-core"
    "@earendil-works/pi-ai"
    "@earendil-works/pi-telemetry"
    "$CLIP"
    "marked"
    "get-east-asian-width"
    "typebox"
    "diff"
    "ignore"
    "yaml"
    "jiti"
)

for t in "${TARGETS[@]}"; do
    SRC="$NESTED/$t"
    if [[ ! -d "$SRC" ]]; then
        echo "  (skip, not present in install: $t)"
        continue
    fi
    DST="$INSTALL_DIR/node_modules/$t"
    mkdir -p "$DST"
    cp -r "$SRC/." "$DST/"
    echo "  copied: $t"
done

# Freeze marker: which version this bundle actually is
echo -n "$INSTALLED" > "$INSTALL_DIR/pi-single.version"

# ---------------------------------------------------------------- 5. regenerate shim
mkdir -p "$SHIM_DIR"

SHIM="$SHIM_DIR/pi"
# Shim uses C:/ style paths so node.exe resolves them correctly on Windows
INSTALL_MIX="$(cygpath -m "$INSTALL_DIR")"
PKG_DIR_MIX="$(cygpath -m "$PKG_DIR")"

cat > "$SHIM" <<EOF
#!/bin/sh
# pi fast launcher (Git Bash) - generated by pi-fast.sh. Rollback: delete this file.
if [ -z "\$PI_OFFLINE" ]; then PI_OFFLINE=1; export PI_OFFLINE; fi
PI_PACKAGE_DIR='$PKG_DIR_MIX'
export PI_PACKAGE_DIR
exec node '$INSTALL_MIX/pi-single.mjs' "\$@"
EOF
chmod +x "$SHIM"
echo "Shim written: $SHIM"

# ---------------------------------------------------------------- 6. verify
echo ""
echo "=== verification ==="

export PI_PACKAGE_DIR="$PKG_DIR_MIX"
BUNDLE_VER="$(node "$INSTALL_MIX/pi-single.mjs" --version 2>/dev/null | head -1 | tr -d '\r' || true)"

if [[ "$BUNDLE_VER" == "$INSTALLED" ]]; then
    echo "[ok] bundle runs and reports version $INSTALLED"
else
    echo "WARNING: bundle reported '$BUNDLE_VER' but npm package is $INSTALLED - re-run this script." >&2
fi

# Check PATH
if command -v pi &>/dev/null; then
    FOUND_PI="$(command -v pi)"
    if [[ "$FOUND_PI" == "$SHIM" ]]; then
        echo "[ok] 'pi' resolves to the fast shim at $SHIM"
    else
        echo "WARNING: 'pi' resolves to '$FOUND_PI', not the shim at '$SHIM'." >&2
        echo "  Fix: add $SHIM_DIR before other entries in your PATH in ~/.bashrc"
    fi
else
    echo "NOTE: 'pi' not found on PATH yet."
    echo "  Fix: add the following to your ~/.bashrc or ~/.bash_profile:"
    echo "    export PATH=\"$SHIM_DIR:\$PATH\""
fi

echo ""
echo "Frozen pi version : $INSTALLED  (marker: $INSTALL_DIR/pi-single.version)"
echo "To update later   : re-run this script (upgrades npm package + rebuilds)"
echo "Temporary online  : unset PI_OFFLINE before launching"
echo "Rollback          : delete $SHIM and $INSTALL_DIR"
